Update Indonesian Localization translation
select2/select2 pull request #6153
Opened 2022-04-13 02:51 UTC by ddevsr

This pull request includes a

- [ ] Bug fix
- [ ] New feature
- [x] Translation

The following changes were made :
- Added removeItem()
- Added search()
- Update searching()
- Update loadingMore()

2022-06-22 02:18 UTC, ddevsr commented
For remove stale bot

2022-10-25 00:44 UTC, kevin-brown requested changes

2022-10-25 00:44 UTC, kevin-brown commented on src/js/select2/i18n/id.js
> +      return 'Mengambil data ...';
```suggestion
      return 'Mengambil data…';
```
The ellipsis change needs to be reverted.

2022-10-25 00:44 UTC, kevin-brown commented on src/js/select2/i18n/id.js
> +      return 'Sedang mencari ...';
```suggestion
      return 'Sedang mencari…';
```

2022-10-25 00:45 UTC, kevin-brown approved these changes

2022-10-25 00:46 UTC, merged